### ISSUE TITLE
Doesn't typecheck on save. 

### ISSUE THREAD

**Issue by seanhess** [facebook/vim-flow#10]
First, thanks for your hard work. 

In the flow examples, it works fine. I hit save, and the quick-check window pops up with the errors. 

In my real project, I added a `.flowconfig`. Running `flow` on the command-line works great, and running `:FlowMake` in vim also works as expected. But for some reason it doesn't redo type checks when I save. 

Here's my .flowconfig
```
[ignore]

[include]
./client

[libs]
./interfaces

[options]
```

Project structure:

```
client/
  app/
    app.jsx
    index.jsx
interfaces/
  globals.js
node_modules/
etc
```

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
